version: '3.8'

services:
  django-template:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py makemigrations BackBridge && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django-template
    volumes:
      - .:/usr/src/app/
    networks:
      - django_template
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db-postgres
      - redis

  db-postgres:
    image: postgres:14.7-alpine
    container_name: db-postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DATABASE: test

    networks:
      - django_template
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  celery:
    build: .
    command: celery --app django_template worker --loglevel=info
    container_name: celery
    networks:
      - django_template
    volumes:
      - .:/usr/src/app
    environment:
      CELERY_BROKER_URL: redis://redis:6379
    depends_on:
      - django-template
      - redis

  redis:
    image: redis:5-alpine
    container_name: redis
    networks:
      - django_template

volumes:
  postgres_data:

networks:
  django_template:
